### ISSUE TITLE
notifications

### ISSUE THREAD

**Issue by mythodeia** [Elethom/PRPrivacyManager#1]
thanks for the library.
i would love to see notification (local & remote) authorization management too

:+1:

**Comment by Elethom** [comment]
Sorry but I'm currently too busy looking for a new job to keep my open-source projects well maintained. Besides I recommend you handle push notification authorisation in another way considering its authorisation mechanism is quite different from the others. Thanks for your support!

**Comment by mythodeia** [comment]
thanks for taking the time to answer.
